AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'prototype_pdfkit'

# Disable some problematic cops for now
Metrics/BlockLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: 'Add the frozen_string_literal comment to the top of files.'
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma